# Generated by Django 3.2.9 on 2021-11-12 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='номер')),
                ('room_type', models.CharField(choices=[('л', 'лекційна'), ('п', 'практична')], default='л', max_length=10, verbose_name='вид')),
                ('count_places', models.IntegerField(verbose_name='кількість місць')),
            ],
            options={
                'verbose_name': 'аудиторія',
                'verbose_name_plural': 'аудиторії',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'група',
                'verbose_name_plural': 'групи',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='назва')),
                ('hours_lecture', models.IntegerField(verbose_name='лекційні години')),
                ('hours_practical', models.IntegerField(verbose_name='години практики')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предмети',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'профілі'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Викладач')], max_length=10, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='початок пари')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.audience', verbose_name='аудиторія')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.group', verbose_name='група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.subject', verbose_name='предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='викладач')),
            ],
            options={
                'verbose_name': 'розклад',
                'verbose_name_plural': 'розклад',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='група'),
        ),
    ]
