# Generated by Django 3.2.9 on 2021-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20211112_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='кінець дати'),
        ),
    ]
