# Generated by Django 3.2.9 on 2021-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='кінець пари'),
        ),
    ]
