# Generated by Django 3.2.9 on 2021-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_userprofile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='кінець пари'),
        ),
    ]
